=== PolitecnicoJIC-SO/Taller01-Ejercicio06/Ejercicio 6.dtd
<!ELEMENT listaCursos (curso)+>
<!ELEMENT curso (alumno)+>
<!ELEMENT alumno (dni, nombre, apellido1, apellido2?, listaAsignaturas)>
<!ELEMENT profesor (nrp, nombre, apellido1, apellido2?)>
<!ELEMENT listaAsignaturas (asignatura+)>
<!ELEMENT asignatura (nombre, profesor)>
<!ATTLIST asignatura codigo CDATA #REQUIRED>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT nrp (#PCDATA)>

=== PolitecnicoJIC-SO/Taller01-Ejercicio06/Ejercicio 6.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE listaCursos SYSTEM "Ejercicio 6.dtd"> -->

<listaCursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio 6.xsd">

    <curso>
        <alumno>
            <dni>1196558974</dni>
            <nombre>Sebastian</nombre>
            <apellido1>Ospina</apellido1>
            <listaAsignaturas>
                <asignatura codigo="AS1">
                    <nombre>Matematicas</nombre>
                    <profesor>
                        <nrp>16548</nrp>
                        <nombre>Alejandro</nombre>
                        <apellido1>Vera</apellido1>
                    </profesor>
                </asignatura>
            </listaAsignaturas>
        </alumno>
    </curso>

</listaCursos>
